<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;

abstract class TestCase extends BaseTestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete("DELETE FROM pembangkit");
        DB::delete("DELETE FROM plta");
        DB::delete("DELETE FROM plts");
        DB::delete("DELETE FROM pltm");
        DB::delete("DELETE FROM pltbm");
        DB::delete("DELETE FROM spklu");
        DB::delete("DELETE FROM spklu_port");
    }

    use CreatesApplication;

}
